### PR TITLE
Moved files around to make growth easier

### PR DESCRIPTION
**Pull request by Eruant**
Firstly each function has been moved to it's own file. This will allow
simpler editing should the number of functions increase

Secondly the tests have been moved next to each file. This makes it
easier to notice when a test is missing, and allows you to find the test
quicker.

### CODE REVIEW

**Comment by skylize** [comment]
I like this idea. Allows partial imports without tree shaking.

**Comment by skylize** [comment]
Not a huge fan of the `f.` prefixes. I think it makes usage less intuitive. This looks awkward:
```js
import curry from 'lb-f/f.curry'
```

Also, for consistency, maybe use named exports for submodules too. So usage like this:
```js
import { curry } from 'lb-f/curry'
```

**Comment by Eruant** [comment]
We can loose the `f` prefixes.

@skylize If we were to use named exports for the submodules, how would you suggest we expose named exports to the main package?

**Comment by skylize** [comment]
@Eruant The main package can also import with destructuring.
```js
import { curry } from './curry'
```

**Comment by Eruant** [comment]
@skylize It wasn't the import I was worried about. It was allowing an export, but that can be done with `export {curry}` if I'm reading the docs correctly.

**Comment by skylize** [comment]
Oh. I see. Yeah, you can actually skip the `import` entirely in the main entry and export directly from the underlying file like this:
```js
export { curry } from './curry.mjs'
```

or maybe it's this, can't quite remember:
```js
export const { curry } from './curry.mjs'
```

**Comment by skylize** [comment]
Actually I like what you did here, exporting on `default` too :+1:

**Comment by Eruant** [comment]
@skylize It's good to know about exporting directly. I may use that in future.

**Pull request merged**
